LAYERS = { "1":"""
"I got bored with four beats to the measure, Professor speech compre{green;ssor}"
"Terminated his tenure to explore a more rewarding adventure,"
"Take a closer look at the bars, you'll see I'm not behind them"
"or in front of them, I'm one of them,"
"Started with a 100, The Game spit 3, I said ""Fuck It!"
"I'ma have to show these niggaz something,"
"Too easy, who'd believe me if I said that it wasn't?"
"The rhyme is a weapon I bust it the Brotherhood got me covered"
"OP orders with coordinates where to drop mortars"
"I drive forward, Sandstorms make my eyes water, 10"
"Skull is a submarine hull, dolphin phones"
"screen calls from places as far away as A.G.C.R.,"
"The rhymes are raw, deeper than yours, you crawled before you walked"
"But didn't think about your thoughts before you talked,"
"We spit for sport, I won, you lost"
"But you paid them off to nail my corpse to a cross,"
"This is ""The Greatest Rhyme Of All Time"" supposedly,"
"1000 Bars it will probably always be,"
"Mentally top heavy, not many can rock with me,"
"Hip Hop could not bench me so they plot to suspend me, 20"
"I said ""Nobody benefits, Everyone perishes"
"I tell them this, They say, ""Here, it's time for your medicine"","
"Imagine being fined over a rhyme? For stepping over the line?"
"When I inspired Hova and Nas,"
"I listened to '44 4's' 22 times"
"I Gave You Power"" God stop my heart if I'm lying,"
"You like Red or White Wine? Let's talk about it I'm buying,"
"Let's talk about the Children of Zion, excuse me if I start crying,"
"The Art Of Rhyming? I've mastered it certainly, surely"
"I'll celebrate capturing it for my Taxidermy, 30"
"From the streets of New Jersey to Germany,"
"To jungles of Angola where most the meat poachers heard of me,"
"The Ice Truck Killer will be observing me perform surgery,"
"Ritual Widow Murder, searching for her urgently,"
"Mix the blood so it don't coagulate,"
"The sex magic won't work if the bitch masturbates,"
"I put her on cloud nine, look at her face,"
"A cumulus lenticularis, a capsule in Space,"
"You will become acquainted with my cryptic language,"
"And my mystic manners, Rip spit bananas, 40"
"Systematic Global geographic systemic Neo-synapsis,"
"Reload the graphics notice I spit it rapid,"
"Advanced Step In Innovative Mobility,"
"Most emcees try to clone me lyrically,"
"My cell chemistry is a mirror of who I am physically,"
"But my true symmetry is energy,"
"The Will of Claude Ashur, the skill of Germaine "
"Father Author Poor Pauper Pastor, more than a rapper,"
"My body is a human machine my dreams filter in between,"
"Just wait until I build my machine, 50"
"Kill you with weed vapour, then a Taser, then a Laser, "
"then a Maser, then a Phaser, then something they call Scalar,"
"That is not dead which can eternally lie"
"And with strange aeons even death may die"","
"But why? Coup de gr?ce for the coup d'?tat,"
"In a man made lodge the Moon Rays replace God,"
"I think I've had about enough of your tough talk,"
"Come over here take my cuffs off, I promise you we'll just talk,"
"No biting allowed just bark, Don't run just walk,"
"Battle Rap there is no such art, 60"
"Emotion manifests Thought, Thought manifests Words"
" Actions & Reality, this is not fantasy,"
"If you question me, you will be detained indefinitely,"
"Your name will be added to the Blacklist Registry,"
"I'm a scruffy old man, with bloody cold hands,"
"On my arm is a tattoo of a sully old brand,"
"If I am not myself, then how would I be?"
"If I do not look tell me how will I see?"
"The Law Of Attraction is attracted to me,"
"The Laws Of Poetry in action is practiced quite actively, 70"
"I look at my face more than anybody else,"
"I still can't recognize myself,"
"I don't need anybody but myself,"
"When I'm rhyming like this I don't need no help, but"
"Thank you for your purchase, these verses have perennial purpose,"
"But on the other hand these rappers are worthless,"
"At least from my interconnected introspective perspective,"
"The more pretentious, the more apprehensive the sentence,"
"You are lazy and you wanna' be the best? You crazy!"
"The Best Train everyday of the week, 80"
"My lyricism amplifies every letter written,"
"Rip The Jacker spitting inside a Zero Vector System,"
"Brain waves reveal High Yield E&D Fields,"
"Chew emcees like I'm eating a meal,"
"A bunch of fake niggaz tryna keep it Pseudo Real,"
"A bunch of fake King Midas' with fools gold grills,"
"My microphone was found where the Mayan Sun Stone was,"
"The Period of Purification in my Poems,"
"Mad Max Beyond Thunderdome under Red Rock,"
"It's no use if you can't use what you got, 90"
"Buried in a mass grave covered in bones,"
"My cell phone number's placed on their tombstones,"
"Your girl Gertrude promised me her servitude,"
"She better do it I don't wanna have to hurt you dude,"
"I'll eat from the same portion as you,"
"Just in case you try to poison my food but I want you to,"
"A Deer Hunter all year if I could spare summers,"
"Fucking your whore of a mother in front of her queer husband,"
"Wide lens wide mattress she's an actress this is Monster Ball practice,"
"I'm Big Billy Bob Black Angus, 100"
"You and I can sit and look at each other, tossing Knowledge "
"back and forth like we was throwing books at each other,"
"I don't care if we're not the same colour nigga I'm your brother,"
"I don't care what you say nigga you're a nigga lover,"
"All cultures come from One Mind, the Universe"
"is not far behind, Waves, Bars and Rhymes,"
"Motivated by the Stars that shine, only lower density"
" life forms get lost in time,"
"I don't care if I make history, I wanna be a part of Infinity,"
"Look at what your Sun God did to me, 110"
"I am energy, I am He spiritually and mentally,"
"The fools who threw away my jewels offended me,"
"As we walk through the archived files of all styles,"
"The East Wing Isle goes on for five miles,"
"More rappers than fans, more vans wrapped than vans,"
"Hip Hop will continue to expand,"
"Poets should be rappers, rappers should be lyricists,"
"The current industry model collapse imminent,"
"This is Hollywood Hip Hop, celebrities adopt "
"little snot nosed bugaboos from off the block, 120"
"Larry King Live, Earthquake right outside,"
"I looked that squarely shouldered man square in his eye,"
"Poetically Paralyzing, Where are you? "
"Are you hiding? No! I am sandbag diving,"
"Do not evade question, please explain to your viewers"
" how there are Space Weapons bigger than Zeppelins,"
"How is it so? Tell the people, they need to know,"
"And if you don't think so, you're a talk show hoe,"
"The grown up who showed up drunk with his own cup stoned as fuck,"
"Who could tell me that this poem is luck, 130"
"You say ""I'm crazy"" I say ""So, tell me something I don't know"
"Something my psyche profile doesn't show"","
"I don't have all the answers I am not in the know,"
"I can only see what is above and only from below,"
"The substratum of reality through the thick cloud canopy"
"How can it be Canibus? Answer me!"
"I approached the podium and delivered my encomium,"
"Nobody applauded the atmosphere was ominous,"
"They feared I would spit, they don't like when I bust,"
"The mucus dried up to a pear like crust, 140"
"From a very cold place called Faraday Base,"
"Right next to the South Poles longest Ice Strait,"
"Food supply low, they speak about going above ground to find mo',"
"I cry out ""NO...do not go!"
"Where the fuck are you going? 400mph"
" wind belts blowing, think for a moment,"
"We got to wait it out, that's what the training's about,"
"We have to survive, that's what Germaine is about,"
"Arctic geography is conducive to astronomy,"
"And the study of celestial bodies, follow me, 150"
"The sheer size of the Academia implied by the rhymes"
"Lead them to believe I was lying,"
"I blasted through the limestone with water mixed with a dissolver,"
"Then I signalled the remaining cave crawlers,"
"Dig a hole for the collateral carnage, battle the hardest,"
"Take out Hip Hop's trash and garbage,"
"Tunnel boring and jacking, water main tapping,"
"I sat there drafting a new drainage plan laughing,"
"Tough, pliable, relatively reliable,"
"The vocation of this undertaking is very viable, 160"
"My lyrical is chemical radioactive residue,"
"I can't rest until I accomplish what I was sent to do,"
"The gross oversimplication of a Jamaican in a basement"
" tracing over diagrams for a tape deck,"
"That evolved into a spaceship, that hasn't been made yet,"
"Cause I haven't been paid yet Not even one pay check,"
"I walked through the valley of humiliation,"
"But Hip Hop started hating, I tried to save them they wasn't patient,"
"Responsibility entrusted, there's only one way"
" for me to prove that I love it, that's why I'm busting, 170"
"If you pursue revenge, dig many graves,"
"Be sure to add your name to the list that you've made,"
"Musically still producing, I got a couple new things cocooning,"
"But Poet Laureate's my New Shit!,"
"Distinguished English and Sophisticated senses,"
"In sync with the Talisman I received from the Temptress,"
"With these lyrics I consecrate the spirit,"
"Whenever I spit it, concentrate you can hear it,"
"I've almost perfected this, I'm one word away from excellence"
", when I find it I'll begin testing it, 180"
"The phenomenal beast, astronomer priest,"
"When the poles shift the Sun will not rise from the East,"
"Wilder than the wilderness, I'm bout to show you "
"who wildebeest Williams is, tou better be filming this,"
"A blast so cataclysmic, it warps the time "
"and space within it, The hours become minutes, "
"the minutes become infinite lyrics, Poet Laureate "
"spit from the spirit from the Sirius Star system ,"
"To observe the Gods, my thoughts graduated to the Stars,"
"To Infinity, listen to the bars, 190"
"The Kapellmeister in the Battle Grinder, created by King Osirus,"
"My psychic wall larger than Chinas,"
"The thirst to rhyme at first hurts like a laborious childbirth,"
"And sounds like Chinese fireworks,"
"Several million years into the past,"
"The primitive future in a world without oil and gas,"
"Focus on two standards when assessing the threat,"
"Number 1 is capacity, Number 2 is intent,"
"The Flood was not an obstacle, I made a raft "
"out of empty milk gallon bottles, for survival, 200"
"Always remember, meet me in Denver,"
"Colorado Springs in the Vandenberg welcome center,"
"Four and a half foot beings with big black eyes,"
"Tried to trap me and extract my rhymes all the time,"
"I perform a requiem on the Eve before Hip Hop ends,"
"And make amends on behalf of my friends,"
"Canibus grab the mic like an energized amulet,"
"Then spit a rap that you can't forget,"
"Oprah Winfrey don't like rap, all I got to say"
" about that is ""She probably don't like Black"", 210"
"I don't blame her, she don't understand it's only entertainment,"
"She'd probably feel different if she wasn't famous,"
"She Traded Places, and her opinions started changing,"
"As Randolph and Mortimer increased her wages,"
"That alone could make a person racist, if not racist with colour?"
"Then material wise how we treat each other,"
"The head of a lion, the legs of an eagle, the wings of a dragon"
", not the sigil, this is for real though,"
"I sit down and think, when I write I can smell the ink,"
"I bow before the desert wall of the Sphinx, 220"
"The ideas have come from God, even I'm stunned,"
"1000 Bars from the real Iron Lungs,"
"I heard Hip Hop was dead, that's not fair"
"Who I talk to?, ""Go he there"" Nasir, yeah "
"Poet Laureate Infinity,"
"I WILL FOREVER BE THE ILLEST LYRICALLY! 226"
""", "2": """
"I procured a small piece of the treasure, collections from a former era"
"Dating back to forever, the warrior became protector,"
"Quoted from the Book of the Law, I don't govern them,"
"I summon them, speaking in tongues again,"
"Started with a trumpet, woodwinds, strings"
"The conductor brings the drums in, fingers trigger the drum kit,"
"Other emcees be nervous or something, rhymes in abundance,"
"Hip Hop Justice, Rappers are captured and punished,"
"Drawn and quartered, liars are denied water,"
"You still alive? I repeat in a revised order, 10"
"Skull is a submarine hull, screen doors"
" protect the motherboard core from extreme heat warp,"
"My mind dives deep beneath yours, Poseidon Trident Seahorse"
"Bubbles form I scream with extreme force,"
"Marineris Trench detour to Ultima Thule,"
"Let me explain what my sonar saw,"
"Upholding the Holy Rosary, patrolling the Open Seas,"
"At U-Boat speed beneath the Tsunami, where I'm supposed to be,"
"Industrialists, civilians, women and children directly,"
"Military chiefs, aristocrats in the buildings, 20"
"Membership is based off your raw intelligence,"
"400 screen video editing with hard evidence,"
"The clinical Professor of rhymes from Pepperdine,"
"Co-signed by GlaxoSmithKline designs,"
"The Universe provided the lighting to see what I was writing,"
"The results were blinding, Lyrics, Timing,"
"Shut the fuck up and stop whining,"
"Instinct controls how you think before deciding, so keep vibing,"
"Swimming naked in the open, a lone shark begins to circle me,"
"Instead of trying to murder me, it tried to flirt with me, 30"
"I got away nervously, talked about it purposefully,"
"Next time I see it, it's going to have a word with me,"
"I guess it wasn't meant to be, under an assumed "
"Identity I resumed PsyOps on the enemy,"
"USA made, field grade steel face,"
"Moving at a Canibus pace in the proto subspace,"
"I am not here to negotiate eliminate"
"The face on the photograph we have in our database,"
"No emcee could rhyme like this, there's no challenge,"
"His Poet Laureateship pontificates balance, 40"
"This lyrical pyramid was discovered by accident,"
"I know I could build it fast if I block and tackle it,"
"Judge me fairly, compare me,"
"To Dante Alighieri's Purgatorio theory,"
"Assigned to train and equip to spit, who's ready?"
"I'll need a volunteer, do I have any?"
"Next year I'll get my SPINGS a master space badge,"
"After that I'll stop flying fixed wing aircraft,"
"Most of you will never understand what I mean"
"My dreams are broken into storyboard scenes, 50"
"Worm screw elevators, descending to the bottom"
" of the volcano's crater, inside the Devil's Chamber,"
"That is not dead which can eternally lie"
"and with strange aeons even death may die"","
"The leaders lies got me reassigned, my loyalty was redefined,"
"They will not be allowed to see the rhymes,"
"What ought to crawl has learned to walk,"
"One Ought Not To Think"" is what Rumsfeld thought,"
"I'ma take you for a walk through a beautiful place called Honey Swamp,"
"We'll shoot hoops at Mosquito Lagoon Park 60"
"The whirlpool of gravity traps me"
"Still allowing me to circle the M51 galaxy"
"Rap for me reduces the stress dramatically,"
"Negative time produces antigravity,"
"Inject the gas into the centrifuge mass,"
"The Teleological Dynamic will enhance,"
"Watch me wet up your weed then bust up your teeth,"
"Make you run for your life like there is a bus up the street,"
"The Dr. and I would meet, at 29 Palms Joshua Tree"
"I always had a lot to debrief, 70"
"Killing my myself, killing my health, rebuilding myself,"
"Nobody ever feels what I felt,"
"Modifying the weather from behind a weather shield,"
"Writing with a feathered quill, getting more ill,"
"The woman who is there, she will take care of you,"
"With Nexium, Avodart, Lipitor, and Theraflu,"
"Rap Music Profession Immunosuppressants,"
"One question per second, One answer per session,"
"Hip Hop made me, Hip Hop praised me,"
"Ain't nothing changed me since 1980, 80"
"Involuntary catalepsy, battle me baby!!!,"
"1000 Bars nigga, after that maybe!!,"
"Murder, murder, murder, kill kill kill drills,"
"Williams was real ill, but now I chill,"
"An asteroid field where every rock is shaped like my seal,"
"__________________"
"I do it for civilians, I do it for the soldiers,"
"Raptors, Comanches, Strykers, Cobras,"
"Back at the TOC with GW Prescott"
"Grid location missile lock lift up the block, 90"
"I gotta spit 'til the story is told,"
"It's a gift, this story is a part of my soul,"
"We shouldn't keep fighting, the Earth is our home,"
"If we destroy Mother Earth, then where we gonna go?,"
"Starving in destitution, dying for retribution,"
"Why would you wanna blow a hospital up? You stupid?"
"Our now fruitless creations used to be in abundance,"
"Like something harder than Tungsten, break your arm if you punch it, 90"
"I ride on a flatbed chariot, four ostriches carry it,"
"I control their movements with lariats, 100"
"Polygraphs flutter, the Lovecraft Craft Lover,"
"Quoting my favourite Inventor, ""I see excitement coming"
"I raise my hand, lightening bolts stream from it,"
"I see excitement coming, I see excitement coming,"
"Unsatisfied, I decide to redefine rhyme,"
"To create product of an applied mind,"
"They say ""we're divided"" I say we're small minded,"
"Right after I said it I moved to a small island,"
"There was no contingency plan given to me,"
"Tell the motherfucker send his transcripts to me, 110"
"Swear your allegiance the tuition is free"
"Swear your allegiance the tuition is free"
"7.83 hertz from the Earth magnified"
"Signal Intelligence emanating from your mind,"
"At the Observatory summit of Mt. Graham,"
"Looking through this starlight scope in my hand,"
"Beautiful longitudinal musical lyrics,"
"Fragments of Olympian Gossip, that is my vision,"
"If A is a success in life, then A must equal X"
" plus Y plus Z no doubt, 120"
"If work equals X and play equals Y,"
"Then Z must be equal to you shutting your mouth,"
"Surprisingly got The John Campbell award for writing,"
"By summarizing that rhyming can be dehumanizing,"
"From the Kinetic to the Energetic,"
"To the magnetic, ultra, electro, and uncensored resonance,"
"I need to be alone, you cannot comfort me like my poems,"
"1000 Bars put me in the zone,"
"The Pope shook, they ransacked Rome and burnt books,"
"I ran back home to hide mine in the woods, 130"
"Salute, I would like to propose this next toast,"
"to maturation barrels I carved from French Oak,"
"The minerals where they grow determine the stability of the flow,"
"I might get drunk and boast,"
"Corruption is necessary, but tell me who's the beneficiary,"
"Which one of us will sing Hail Mary?,"
"Hip Hop supposed to be about endurance,"
"But every time you rhyme not just when you touring,"
"Acupuncture point or plus, is not enough,"
"I need more pain so I can pretend to be tough, 140"
"The facts too acute to repute, or debate,"
"My face is a slim sleek gas mask shape,"
"My dream was identical seven nights in a row,"
"I saw a sideways 8 wrapped around a microphone,"
"The window is closing, from the other side it looks l"
"ike it's opening, where am I trying to go with this?,"
"Fire and Ash fallout, that's what it's all about,"
"We must construct a shelter, then build a wall around it,"
"All the parents want to do is look at the body"
"But, it won't happen 'til after the official autopsy, 150"
"A good psychological environment for science,"
"I'm memorizing and visualizing peace and quiet,"
"Father Author Poor Pauper has poor posture,"
"As filthy as the collar of a dirty grave robber,"
"This is my unacknowledged special access project,"
"Time reversed waves in nonlinear optics,"
"The coral reef is changing from green to amber,"
"Scientist scramble to come up with new answers,"
"The truth is well within my sphere of pursuit,"
"But I'm unprepared to take action just like you, 160"
"The innate need for Canibus to be professional,"
"Make it difficult indeed for me to connect with you,"
"Greetings and Salutations, my equations are inundated,"
" with information, Electro Cranial Stimulation,"
"Burn skin off face, burn face off skeletal plate,"
"Plasma Ray Gun is just one explanation,"
"Man Made Membrane roofing remediation,"
"Any and all entry points have immigration,"
"One meter beside the Hubble outside the bubble,"
"The effects of gravity on my muscles were quite subtle, 170"
"I do what I want to do, I have always been that way,"
"Because I have always thinked that way,"
"Attach the piezoelectric transducer to your computer,"
"Poet Laureate is the future!!!,"
"Pulsating Lights and Sounds surrounds spirits,"
"Bio Oral Beats, layered underneath lyrics,"
"250 thousand cycles per second, for Dolphin hearing,"
"The Electrical Optical Coupling Gear is effective,"
"88 Kilometres above the planet,"
"My rhymes harness a power beyond your understanding, 180"
"The Gods began to call me, I looked up a star fell towards me"
"And scorched me to a metaphor freak,"
"The authentic Command Doctrine of George Washington"
"Himself, GW I'm positive it's him,"
"I proof read my writtens, eat a chicken with the skin missing,"
"Spend the whole night out binge drinking,"
"______________"
"______________"
"First it was Vote or Die, now it's don't vote"
"Why? Weed is now legalized, are you high? 190"
"Rhymes compartmentalized seperatized to prevent"
" bootleg pirates, be my guest keep trying,"
"The bird chirps dying in the dirt because the earth is hurt,"
"But not before I start cursing first,"
"Not so fast Mr. Iconoclast,"
"If you don't leave the bottle outside you can't pass,"
"Gather the evidence, then give it to the President,"
"Don't reprimand him, ask him for help next,"
"A lamp with no electrode will not glow,"
"We need some new bright ideas that we did not know, 200"
"You cannot fold under the political pressure,"
"You gotta take prudent and precautionary measures,"
"I think of rhymes in my mind when I autograph sign,"
"I can't wait to sign an autograph for the last time,"
"A Luciferian web, everyday we are burying dead,"
"Every colour in America bled,"
"This is empirical evidence of the greatest collection"
" of Canibus sentences, you'll never reach the end of it,"
"Fire and forget, rhyme for respect,"
"I didn't get that so I wrote Poet Laureate, 210"
"The Hubble Space Telescope images changed Bis,"
"And nothing on this Planet can dissuade this,"
"They left me dehydrated by the Nile River naked"
" But I made it with the passion of a Microphone Patriot,"
"Music is my bread and butter, why should I suffer,"
"My publicist said she could get me the Time Life's cover,"
"The spin off from the Press should be able to feed you,"
"But I declined 'cause I'm familiar what greed can do,"
"I can not lose or win, I would only like to"
" be remembered as the dark skinned Lizard King, 220"
"Into the bottomless pool of Poetry I plunge,"
"Let it be said, let it be written, let it be done,"
"Publicly coming forward with my metaphors to share,"
"About the space serpents flying around in the troposphere,"
"Poet Laureate Infinity,"
"I WILL FOREVER BE THE ILLEST LYRICALLY! 226"

""", "3": """
"I spit at a thousand KIPS, kilo tons of pressure"
"Everyletter is measured in such a way you will remember,"
"December, 21st 2012 is the code"
"It was placed on the Mayan Sun Stone to puzzle them,"
"Starting with some numbers, the code cracker started crunching"
"I better have some results by the months end,"
"Really, Deep Blue computes deeply and does it,"
"What's the answer to Universe? Read me the numbers,"
"In the summer the Polar Manitoba's melted by lava"
"A team of ER doctors climbed aboard the chopper, 10"
"My skull is a submarine hull"
"I empty the ballast tanks I could smell the shit from the seagulls,"
"The Rear Admirable participated in battle every war"
"At least half of my crew were injured every tour,"
"We thought close support from the Navy Carriers and Air Force"
"would give us all what we needed, we were wrong"
"Canibus is notably known Globally,"
"My verbal sorcery somehow tries to talk to the beat,"
"Lyrically not ready, dress right dress, not messy"
"My muscle memory make me bomb squad steady, 20"
"You cannot contend with this when I let it rip,"
"Eyes, ears, nose and throat specialist Professor Bis,"
"The sublime chakra one through nine, through the spine"
"Induce the rhyme, internal fire produces the high"
"Recite 33 3's 33-3 times for twenty four hours"
"Twenty one thousand Nautical miles,"
"Ahead of my lifetime I write and recite rhymes,"
"Deja Vu in the booth is the truth, when you apply it,"
"Devine design, a miracle of Metallurgy,"
"Every clergy member from Mecca who heard of me worshipped me, 30"
"From the shores of Normandy to the Turkish streets,"
"To the bluest oceans glowing on the Persian beach,"
"Nuclear Biological Chemical emergency"
"I purchase the beat then mix the spit with the mercury,"
"The DJ grabs the acetate out the crate,"
"Mix the dub plate, the BPMs fluctuate,"
"Nobody can hold me back, my flow bloviates "
"into a spiritual shape and co-creates rap,"
"Cold callous chronic chemical imbalance,"
"Smoking a chalice in the Rabbit hole with Alice, 40"
"The target appears in brackets, I attack it,"
"Access then egress then quit this rap shit,"
"Commander of the symphony when man meets ministry,"
"Finishing my Archeogenetic Rap Facility,"
"They can't battle me so they'd rather embarrass me,"
"By being mad at me they commit microphone heresy,"
"I am still the Master, as handsome as my unborn Grandson"
"Rip The Jacker, call me grandpa,"
"As odd as it may seem, the Microphone Fiend"
"Is God of the Hip Hop regime, Planet Rock Supreme, 50"
"Kill you with green Lasers, evaporated weed vapour"
"Electromagnetic Scalar, then something they call a Maser,"
""That is not dead which can eternally lie"
"and with strange aeons even death may die"""
"Meteors fall from the sky, The Mars God looks at my eyes,"
"Controlling my heart, controlling my mind,"
"O Lord, tell me what to do, tell me O Lord,"
"I've mastered the art of rhyming now I am so bored,"
"My pain, my joy, my thoughts, I've passed them on through songs,"
"Respond to me and I will answer to your call, 60"
"Emotion manifests Thought, Thought manifests Words, "
"Actions and Reality, That's how it has to be,"
"In front of me, on both sides and in back of me,"
"I hear them talking 'bout battling me in the whisper gallery,"
"The chain of command blames the unseen hand,"
"The Galactic Plane has a Galactic Plan,"
"I look up in the sky to see if God is judging me,"
"Then suddenly I feel Fatima and Medjugorie come to me,"
"Sitting down at the mixing board comfortably,"
"They begin to study me, by showing me worlds I would love to see, 70"
"My body did not melt beyond the Van Allen Belt,"
"I was transformed into a spirit with no shell,"
"I could move about freely, I rose, I fell,"
"The coldness of heaven is like the coldness of hell,"
"Metaphoric Sun Worship, pulling me like planet inertias,"
"Words blinking like the text edit cursor,"
"Sentences sometimes too sensitive to make sense of it,"
"Layer upon layer upon layer unedited,"
"You lazy and you wanna be the best? You crazy!"
"The Best Train everyday of the week, 80"
"Propulsion system gravity driven, white hot thermal external vision"
"Every lyric got a wormhole in it,"
"Saint Germaine is real, Germaine is a sage for real,"
"My sigil is a double headed eagle seal,"
"Normal life is not real, we are just cogs in a wheel,"
"We work, we hurt, we search, we feel,"
"Microphonist that utilizes the study of Conics,"
"Circular motion in both the para- and the hyperbolas,"
"Tiger Woods knows this, everytime he plays golf he shows this,"
"A true master at The Masters in focus, 90"
"In my time of need, I am not alone,"
"I was told in a dream by Cthulhu from his tomb"
"Try to hurt me, I'll murder you, lay you down vertical,"
"Make your life purposeful, germinate the earth with you,"
"My black goggles covered with Bat Guano,"
"I'll hang from the ceiling and watch you, act hostile I'll pop you,"
"Rap Music and those who listen to it don't owe me nothing,"
"I don't want nothing from you, not even your judgement,"
"The Philosophic maverick the massive knowledge magnet,"
"Underwater sea lilies where I get my magic 100"
"Matricidal motherfucker homicidal hustler,"
"Filibuster, never been a Wikipedia lover,"
"If I were you I wouldn't waste my time reading rubbish,"
"It might turn you into a media puppet, but fuck it"
"Leviathan divides the suspect zero sign,"
"Therefore Canibus rhymes for all time,"
"Metaphors and Rhyme is poetry by design,"
"But poetry continues outside the timeline,"
"Unnatural battle ability, the enemy tried to imprison me,"
"But they would've been better off killing me, 110"
"Theoretically Schiaperrelli has mentored me,"
"With motifs of illuminated speech and wizardry,"
"Over The Horizon Radar Rhymes"
"Patent number 4686605"
"Sound pours out of the ground across the land,"
"Jethro Tull was mauled by the God called Pan,"
"Creative writing and rhythm, grammar and composition,"
"Don't ignore me, ignore the fools who tells you don't listen,"
"To you it shouldn't sound like I'm quitting cause I'm not,"
"If I am to continue it's up to Hip Hop, 120"
"Weary of body and mind, tired of swimming against the tide,"
"Why swim or walk when I can glide?"
"Zero Gravity exercising, requires expert timing, "
"For Sky Diving, my call sign is Flying Wing,"
"An impossible profession, St. Germaine was made"
" to explain the lesson with a 1000 Bar message,"
"Now you may go, you have graduated, now you may know,"
"Tell the world exactly what you were shown,"
"Sure enough, Sesame Street poems brought to you by Sears Roebuck,"
"Countdown forty eight months, 130"
"Does it amaze me? ""No!"" Does it phase me? Maybe a little yo,"
"We gotta find a way to generate doe,"
"The promoter won't pay me what I want for a show"
"Why do it for free when I'm worth my weight in gold?"
"Mind, Body and Soul inseparable, incredibly,"
"Proto plasma recycles the matter perpetually,"
"Hip Hop became boring, lyrics seem more like"
" a vestigial organ, but they shouldn't be important,"
"The diaphragm, the thymus, Activate the latent powers "
'that reside inside us with 13 chakras 140'
"You get the Guantanamo Bay, The Alcatraz Way,"
"You heard what I say? These pigs gotta pay!"
"I steadied my approach, this supposed to be a NO FLY ZONE"
"Black Sheep Squadron with strobe light hoes"
"The Hurricane's eye open, gale winds blowing"
"Moses on a row boat floating in the ocean,"
"I figured out, how to save water in a drought"
"If we save the right amount I know we can make it out"
"The ever expanding mind commanding body, do you copy?"
"The Quantum biology biopsy, 150"
"My austere designs are so ahead of their time,"
"Even when you press rewind you're still left behind,"
"Father Author Poor Pauper, breathes to draw Prana"
"In a yoga pose tryna get close to your mama,"
"Your ear cartilage has been targeted"
"The bombing will commence, don't be a bitch nigga you started it,"
'On the Sabbath I write preplanning for the Planet'
"Drawing mechanics, suspended in space as holographics,"
"Scientifically Quantifiable, megalomaniacal"
" viable style it's like trying to ride a Bull, 160"
'The lyrical inimical is miserable because I\'ve built a citadel'
"of syllables that made me invincible,"
'Am I a mad man or a mason? A Patriot or a Pagan'
"West Coasting in a 64 with Daytons"
"The propulsion system matrix poorly calibrated,"
"I'm waiting on the parts special order replacement,"
"Battle rap is just aimless entertainment"
"Second Round K.O. was one of they favourites, fuck all the haters"
"My luck was crushed, I felt like they fronted,"
"My heart kept pumping, I had to do something, 170"
"I turned the page, wrote a turn of phrase,"
"Verbal X-Rays, they say ""I don't burn I blaze"""
"Don't look at it like winning or losing, in '98 it was amusing"
"Poet Laureate's my New Shit!,"
"Time keep on slipping, the Ripper keeps ripping,"
"But right now my image stands still in a prism,"
"My light reflects like a mirror, I choose to share it,"
"The Precession of the Earth is nearing, I'm preparing"
"Assessment and Planning things"
"Should I put mustard on these sandwiches, a fathers job is so challenging, 180"
"My pupil size increase, constriction and velocity decrease,"
"You can't Emcee take a seat,"
"What are you building Bis? Is it a flying Silver Disk?"
"If you ever leave you'll be missed,"
"I tear through the Galactic drift, I travel 10 digits"
"in 10 minutes, now that's some shit!"
"You think that's fast? nah, that's faster than you think"
"By the time you blink, the whole Universe shrinks,"
"A word to the wise, try to keep your eyes in the skies,"
"Try to keep your ears on my rhymes, 190"
"The magic reminded that the fire will not expire,"
"Pyrus Sidonious gives me energy when I'm tired,"
"The Sun is so bright my eyes hurt"
"I'm forced to look downward to see inside the Earth,"
"I thank Mother Gaia for bearing us green grass,"
"But it won't last we're killing her with greenhouse gas,"
"You said ""the best shouldn't ask for respect"","
"Is that correct? Yes could you please speak up, I SAID YES!"
"I hold Hip Hop responsible,"
"Every magazine writer that wrote bullshit in his article, 200"
"Gone 'Til November? I'll be gone forever,"
"I made these bars so you ALL could remember,"
"The illest MC to put it all on the line,"
"My career was crucified but I'm still alive,"
"Sky scraper spaceships, wide crater dry lake beds,"
"""Resistance is futile"", they said,"
"I bear clutch the pen, my girlfriends jealous again,"
"So intimate when I write it's a sin,"
"Electromagnetic rap flytrap,"
"There's no way Earth you can get around that, 210"
"This is a no brainer, stop the complaining,"
"If Hip Hop is dead, I came here to save it,"
"Pages upon pages, everything I've created ,"
"The bar was below basic, I had to raise it,"
"I did it for my Fathers, I did it for my Mothers and my Brothers,"
"I did it for the world to discover,"
"My poetry is peaceful, aggressive but regal,"
"Progressive to the people, I hope the words reach you"
Dr. Watson and Crick found an third strand in the DNA helix
"So you're not what you think, 220"
Metronome Man will never take commands from the drum
"The beat is my slave and it will behave as I want,"
"Cheers! Spill beer on my bear skin chairs,"
"I shed tears, I loved Hip Hop all these years,"
"Poet Laureate Infinity,"
I WILL FOREVER BE THE ILLEST LYRICALLY! 226
""", "4": """
"Nobody do it better, there ain't a truer Ripper,"
"I did this separate imagine what we could do together"
"Inspired by God, inspired by the suffering,"
"Was it done by a prophet? It must of been, who was it then,"
"Rip the Jacker, hot but cold blooded"
"Many utter the name but very few love him,"
"33 is the number that enlightens the Brothers,"
"Insight to the fullest, that could brighten the dullest,"
"The ramifications are awesome, what should we call it?"
"I call it my unacknowledged special access project, 10"
"Skull is a submarine hull,"
"In a cave below ground with a painting of Cthulhu on the wall,"
"Necronomicon grimoires, open the doors "
"to the vortex that reaches from here to beyond,"
"  ___"
"  ___"
"The power to control thoughts however remotely,"
"Through a term I'd like to call ""Pulse Detonation Poetry"
"The results from SETI, very interesting,"
"I briefed the committee they told me to stop the testing, 20"
"My team was credited, turned over the evidence,"
"But not before I could leverage it, promotion to President,"
"Cover me, 8 point sighting device for the eyes,"
"Fire!!! Transition if you go dry,"
"Close your eyes, ritualize, spit your rhymes,"
"Without trying you can shift your mind,"
"Canibus altered the sequence of nucleotides,"
"Neuropeptides only get high off just mature Wine,"
"Start timing, Atomic Clock keeps time perfectly,"
"Mrs. Guutoff my band teacher always would work me, 30"
"Polyester pants, big fat ass,"
"I loved that woman so much, I paid attention in class,"
"My Spanish teacher Mrs Booker had an ass too,"
"Why am I talking about this to you?"
"One day this will be known for now it must wait,"
"I still love them both and I never forget a face,"
"At the time I used my Beta waves more than my Theta waves,"
"Then there was greater way I learned at a later date,"
"The rate of learning began burgeoning and wouldn't let up,"
"Mommy noticed my vocabulary had developed, 40"
"Telencephalon olfactory lobes I had to practice,"
"When a woman has her period I smell it on the mattress,"
"It got to be difficult for a woman to live with me,"
"I know my history, but what could that mean specifically?"
"The story of Bruce Lee, I died in my sleep"
"I was weak, it happens with every girl that I meet,"
"A Clairvoyant Technique, using X-Ray refraction"
"Not only can you see into the future, see past it,"
"But I don't know what it means I pass the DataStream along to my team,"
"They say it's more than a dream 50"
"Killing caused by poisonous vapours, Lasers, "
"Tasers, Masers, Electromagnetic Scalars,"
"That is not dead which can eternally lie"
"And with strange aeons even death may die"","
"Listen to the rhymes, the rhymes equal Pi,"
"If I had a piece of the pie I could buy Dubai,"
"Rip the Jacker was born, the bow was drawn,"
"Spit a 100 bars before you could run a 100 yards,"
"I seen a mushroom to the north, from my porch,"
"It was odd, every dog in the neighbourhood barked, 60"
"You wanna stand there and talk? A blast wave gonna "
" tear more than your roof off, nigga c'mon!"
"It is my understanding, when I'm high I'm channelling,"
"But when I'm out with the family I am animal handling,"
"Observe the man with the Microsoft strand,"
"Or a 5th or a 6th, 'cause way more advanced,"
"I remove the veil from in front of me, suddenly"
"The roots of my discovery uncovered skulduggery,"
"I am not innocent, but you cannot punish me,"
"'Cause I know what the world wants to see, tragedy, 70"
"What is Germaine determined to ascertain for his self?"
"Few of the same elk have known what I felt,"
"There's a Proverb that goes ""One should know thyself"
"Before one can know the world"", so I showed myself,"
"The unidentified submersible, looked like a giant turtle half circle,"
"Yo, I need to stop smoking purple,"
"Requested, selected, elected, but that's only impressive to the expert,"
"Who know how to manipulate my message,"
"You lazy and you wanna be the best? I repeat,"
"Don't talk about consciousness being conscious-less and weak, 80"
"If I die and you happen to wake up, I'm still alive"
"Please explain my complete life story to my children,"
"Photo stills of the cryospill,"
"Solarized film revealed that there was a biofield,"
"Fuck a record deal, my training is real,"
"Look at the sword I wield, you will taste my steel,"
"Phase I, sign the MOU, pursue more voters"
"There's three more phases that I think you should know,"
"The Phase II, build the force, Phase III, sustain Ops,"
"Phase IV, transition of all Border Cops, 90"
"Do, Re, Mi, Fa, Sol, La, Si-Do"
"These are the tones that will activate the ohm,"
"No telling if it will bring out the best or the worst in you,"
"It would be a miracle if I was merciful,"
"Are you food for the moon? Or are you in the mood for doom?"
"Furniture moves when I walk in a room,"
"Stryker Brigade Driver, sometimes I was Gunner,"
"Checkpoints required all the concentration I could muster,"
"Special Weapons and Tactics, Professional Assassin,"
"I don't know what he does for a living ask him, 100"
"I kneeled before Congress and begged for money,"
"Submitting specifics about the operation I'm running,"
"You gotta love it, what was it called? The G8 Summit,"
"Never heard of it"", no details are public,"
"The relative radiance of the rhyme make it shine,"
"Increase the star wattage with longer cycle time,"
"Yeah, I bust the rhymes but I customize the lines,"
"And by the looks of things I did it just in time,"
"I marched from the Halls of Montezuma to Tripoli,"
"Physically this mission objective is killing me, 110"
"I submit to the will of the creator willingly,"
"The possibilities present a probable infinity,"
"I looked into LL's eyes we both cried,"
"Meteors immediately fell from the skies,"
"I've apologized but I can't change who I am,"
"I can change future, can't budge the past,"
"Them pretty ass lyrics is for bitches with acrylic,"
"Only fake niggas catch feelings over silly shit,"
"Sports locked and loaded, zero you in from the pillbox,"
"Williams! How many kills you got? 120"
"The uniforms match so we all look the same from the sky,"
"The only time they notice the difference is when we die,"
"Is dying a wise thing? What about trying?"
"What about the family members back home crying?"
"Manmade weapons Starship Captain etc"
"George Lucas showed me a full sized replica,"
"Circled for a fly over in a black Kiowa"
"Five soldiers including me and a pilot called Noah,"
"He passed over a top secret dossier folder half opened,"
"I noticed the words MOSES and CONUS, 130"
"MOSES is a new weapon system secret code,"
"CONUS is the continent of the US, I suppose,"
"The jump light lit up, Master Chief said ""Let's Go!"
"All right men this is what we train for,"
"Williams you gotta go first, ""if you say so, HALO"","
"High Altitude Always Stay Low,"
"Gale Winds blowing, this might be the death of me,"
"The Airborne unit in the back of me jumped out next to me,"
"Gold chords from the organ cut down your swordsman,"
"Tell everybody to shut the fuck up when I'm talking, 140"
"The 1000 Bar race at an unrelenting pace,"
"Just in case Humans ever get to World War 8,"
"Do you believe in fate? Then how do you know?"
"When you finally get there, where will you go?"
"This ain't no joke, you think I'm joking,"
"Everything frozen, melted, destroyed, broken,"
"Only the chosen find a way out,"
"Everybody move out! Make sure to stay off the main route,"
"Satellites watch me they think they got me,"
"Right hands turn left shoulders around but it's not me, 150"
"Atmospheric Reentry a flying sighting, looked like lightening,"
"Striking blind, what the fuck's frying?"
"Comparative image sharpness between artists,"
"I don't think you know what you're about to get involved in,"
"Give you a quadrillion dollars to be a partner,"
"If you are still worshipping money I think you are Godless,"
"Sulphuric Nitric Acid eat through the Labyrinth,"
"The foundation is cracking, we must take action,"
"Basic Instruction Before Leaving Earth, B.I.B.L.E."
"I take shelter in an old Missile Silo, 160"
"Hip Hop is blackened pot placed next to a kettle,"
"With my logo in it, a rigid rehomogenized metal,"
"Millions of you are unfamiliar with what I'm saying?,"
"Discuss it with your Chemistry Professor he will praise it,"
Tri Quad Quintangulate where did the signal originate?
"Try to find out more information,"
"The internal atheist outside the Matrix,"
"Sophia Stewart offered me a pill and said ""take this"","
"She asked me if I was followed, I told her I wasn't,"
"I didn't know the spy that sold me out would be my own cousin, 170"
"Populace uniformed is a populace of slaves"","
"Washington didn't say it quite that way,"
"But it's something like that, you get the point I'm assuming,"
Poet Laureate Exclusive New Shit!
"The message said ""We should meet somewhere clandestine"","
"Professor keep heading East to the Best Western,"
"Do not loose your bearings, keep checking your direction,"
"Start Session point 666 arc seconds"
"The budget is huge, I have doubts about spending it,"
"Concerning Cyclotronic Resonance, patents are pending it, 180"
"Canibus AKA ""The Spitzberg Beast"","
"Gave his Bicentennial Speech on Emerald Peak,"
"You'll need a first aid kit for the verse I spit,"
"I am cautiously meticulous but artfully brisk,"
"A change is beginning every molecule is spinning,"
"Lyrics imitate the art, art imitates lyrics, can you hear it?"
"Signals bounce back and forth like a mirror,"
"With flawless error, like that forever"
"Surface the air radar tells me where they are,"
"Are they far? I patiently watch the sweep arm, 190"
"We can find them but they can't find us,"
"Just below Mach 3 the rhymes ionizes,"
"I'm hooked on Hip Hop, I can't live without it,"
"You can mix this song a thousand ways I don't doubt it,"
"The daughters of man locked in prison camps,"
"With the sons of mothers that are too weak to dance,"
"At least we notice damage, what do we expect,"
"The coming super storm is gonna wipe us off the map"
"But that is not possible, that's sounds completely illogical,"
"You must've been kicked the fuck out of school 200"
"Always remember the Reptilian agenda,"
"No Pulse Rendered"" in the earthquake's epicentre,"
"I found fluoride in my water supply,"
"At the time I felt a total apathy towards dying,"
"The ungrateful dead reoccurring images playing in my head,"
"I was told to memorize what I was said,"
"With this salt I consecrate this water,"
"may whatever it touch receive Hallowed Light coming from Them."
"With this sacred water I consecrate this Talisman"
"so that it will make me Poet Laureate"" 210"
"Otherwise I'll be so depressed, oh well no regrets"
"I been toe to toe with the best, I 'Know the Ledge'"
"I accept all cultures, colours, creeds and races"
"Life is Life no taxonomical classification,"
"No corruption, no disruption, no destruction, no budget, no nothing,"
"It's never that easy, you just gotta trust it,"
"A leader that feels beleaguered to teach the youth,"
"The Youth will refuse to follow if they don't believe you,"
"There is strength in numbers there are numbers in strength,"
"Nothing good comes from hatred, Love's the missing link, 220"
"Even if I am in a minority of one,"
The truth is still the truth no matter how it's spun
"My mind is prepared, Hip Hop is impaired,"
If you disagree with me then yours isn't there.
  ___
    ___ 226

""","5":"""
"I rock rhymes for your pleasure, you listen at your leisure,"
"I only record it once you listen to it forever,"
"The fish hook stuck in your jaws, the feedback was not positive,"
"Human Hominids fishing for compliments,"
"Started with a nugget, the budget snowballed into something,"
"Above ground running not underground covered ,"
"Breath easy, regulate the pace see if they love it,"
"The Poet Laureate puppet with a message from ""The Others"","
"The aura describes the forces, I'm too involved to divorce it,"
"My internal compass points me northward, 10"
"My skull is a submarine hull,"
"Calling whales with whale song, creating basketball size hailstorms,"
"Water World under water war protected by the Jericho wall,"
"With surface permutation of the permafrost,"
"My war birds are grounded, their wings have been burned off,"
"I'm not concerned though, it's only the first lost,"
"Poetry Poetry Poetry Poetry Poetry,"
"Poet Laureate infinity now you know it's me,"
"Yeti riding a Triceratops with Elephant netting,"
"Attending Black Widow weddings dressing in gossamer webbing, 20"
"Pretending, experimenting, they call me a heretic,"
"A derelict cherubim seraphim protecting America,"
"Height, weight, eye colour, skeletal structure was designed,"
"I circle my flight instructors in the skies as they fly,"
"22 times, to show them I have plenty new rhymes,"
"Poet Laureate will prove it to you all in due time,"
"Don't be upset with Canibus yet, the kid just want respect,"
"You been a success but what do he get?"
"Politics and Perjury bring out the worst in me,"
"But I don't take it personally, even though it's hurting me, 30"
"The key maker turns the key, those observing me keep cursing me,"
"They aren't worthy of a word from me,"
"I spit the truth, Rip the mic, Rip the booth, Rip you too,"
"Rip the Jacker is proof I Ripped through,"
"It drives me insane when a woman wears lace,"
"The current gene structure is 46 pair based,"
"Her heart rumbling and thundering like Captain Nicole Malachowski"
"From an airbase, on a clear day,"
"Ok I'm a pervert, It's time to fess up,"
"I might be looking for a leg up, but I won't touch, 40"
"Closet sadomasochist sexual pacifist,"
"I like to role play but I only play masculine,"
"Victory over injury a victim to misery"
"The myriad of my metaphors make me a mystical mystery"
"I'm a giant in the industry just over 5 ft,"
"Even my photo ID don't look like me,"
"The NASA contractor with a satchel of answers,"
"I passed up the Nobel Peace Prize for my passion,"
"Democracy Rules Everything Around Me, D.R.E.A.M.,"
"Another fucking acronym, just what I need, 50"
"Killing me with phrases that were designed to put me into dazes,"
"As worthless as stupid junk mail is,"
"That is not dead which can eternally lie,"
"and with strange aeons even death may die"","
"The Squid Faced God is difficult to describe,"
"Those of weak heart and mind shouldn't even try,"
"In a town near Kadam and Kakrak Jahlalabad,"
"I pray in a hut constructed from Sago Palm,"
"Astoria Oregon Fisherman Poets got lost,"
"Looking for Paradise, it only exists in the heart, 60"
"'Cause emotion manifests Thought, Thought manifests Words, "
"Actions and Reality, But what is attracting me?"
"The overseer of poetic antiquity,"
"The Victoria and Albert Museum kept them for me,"
"Pythagoras, Dionysus, Loki and Pan,"
"They have enlightened me thru song to understand,"
"The multiplex meshing multiple messages is too much for me,"
"Truly there is too much to see,"
"I'll mix one for you, then one for me,"
"I'll mix some for the street, mix 'til my thumbs bleed 70"
"A stationary pulley drawing from a wishing well,"
"The Genie gave me more than three because I listen well,"
"Conflicted and confused but completely compelled,"
"To celebrate my birthday alone in the year 2012,"
"I hope I am not alone, that would be terrible,"
"If I am celebrating then that be a miracle,"
"In a newly ordered world living in shit,"
"No matter how good or poor your English is,"
You lazy and you wanna be the best? You crazy!
"Poet Laureate is reserved for the name G, 80"
"e-r-m-a-i-n-e, Will-I-Am"
"The name that my precious mother gave me,"
"The world came to know me as Sir William,"
"The man of steel with a Smallville build with the illest ,"
"Some of my thoughts align with Einstein himself,"
"I wanna know God's thoughts too, the rest are details,"
"Lyrical Fitness is no secret of course but,"
"The secret to creativity is hiding your sources,"
"Preserve the sanctity of the Soldiers in Iraq,"
"Do not blame them and hold their humanity hostage, 90"
"Pray for the families that want them home,"
"Pray for the families abroad that have lost their homes,"
"Who have lost their faith, who have lost their hope,"
"Who have lost their point, who have lost their own,"
"Yo! Calm the fuck down, I shouldn't have to curse at you,"
"Hydrate as much as possible, drink a lot of juice,"
"Fucking bummer, no armour inside the Hummer,"
"Gotta hug a motherfucking sandbag for cover,"
"Now I'm self employed, still gotta pay taxes,"
"Cashless, bankrupt, ain't got no assets, 100"
"From the gutter to the gallows no media coverage,"
"'Cause I don't want it, that's why I'm rarely seen in public,"
"President Poetry, the popular obedient Pundit,"
"That's right, you can take this job and shove it,"
"I dictate a scribe that causes the court stenographer to die,"
"Brewing hot tea with honey and lime,"
"How's my driving? Run you off the road smiling,"
"1-800-RoadRage, Start dialling,"
"The snake will grow feet and stampede you to your defeat,"
"You are weak, you lied to us all in your speech,110"
"Symbiotic indeed, the host bleeds,"
"Parasites attach to feed fulfilling antiquated needs,"
"Rock climbed the slope shaped like a stop sign,"
"In record clock time, Hot Lava lock rhymes rock slide topside,"
"How does one ever really perfect such a craft?,"
"You're obliged by your curiosity to ask,"
"Cubism and Futurism writing amusing lyrics,"
"My opinion of your opinion is you can't be serious,"
Test driving my principle findings
"By designing a new style of rhyming you can take home and try out, 120"
A 100 Bars per hour sometimes I doubled the writing
"Secret signature timing was the hardest part to figure out,"
"Agonizing, the pain of the migraine biting my brain,"
"And everything inside it I can't explain but I'm trying,"
"I heard this before, I can't remember who said it,"
"We hear from 1000 to 20 thousand cycles per second,"
"Straight out the freak show no pre show,"
"Limited oxygen when I rhyme fast you breath slow,"
"VFR stands for Visual Flight Rules by the Book,"
"You should know this even though it don't concern showbiz, 130"
"Because when in Rome, walk as a Roman,"
"Obviously you can see you've made the wrong choice,"
"Fraternize but don't do it in the wrong tone of voice,"
__________________
"A bad boy with bad toys made from new alloys,"
"Readapted from a crashed disc and asteroid,"
"My shelter is not far, you can borrow what you need,"
"The bunker doors sequestered beneath the tall tumble trees,"
"After the Matrix, Agent Smith continued his movement,"
"The same bullshit, that humans are major pollutants, 140"
"Assemble the Gatling gun, spin it see if it spun,"
"Weapons check correct, I'm done, next one,"
"My rap room is an 8 by 14 underground base,"
"Hypercube microphone booth in a vacuum of space,"
"Extraterrestrial Isotopic ratios,"
"A broke Scientist in his Lab with no place to go,"
"All these conscious rappers ain't saying nothing,"
"Matter fact they have no constituent function,"
"Mix this record different, you'll hear me call names out,"
"It's played out but there must have been alternative routes, 150"
"The Geneva Protocol Advocates are so sloppy,"
"A human being is not anybodies property,"
"Reading body language in a Zero Gravity environment,"
"Is much easier said than done, if you're trying it,"
"Attending the Opera with a Pompous Ego Monster,"
"I can barely take my eyes off her big old knockers,"
"Integrated in an existing clothing ensemble,"
"My Saratoga Suit is Military Garment,"
"The Quarantine Isolation Unit is where I house it,"
"My team and I salvage the work of Dr. Fritz Albert, 160"
"If the prototype works, there's no telling what I will do,"
"I'll have to get a new plane, a new pilot and a crew,"
"Creatively I have never been to this level,"
"First I'll put you in a sideways 8, then a pretzel,"
"Password please have patience verification,"
"I repeat, ""What's Your Character String Verification?"","
"Infrared spectral observation from the Space Station,"
"Before you take a break, I'll need you to list and name them,"
"Dock the Kliper Craft at the preliminary designation,"
"Tracing the Detection of Submicron Radiation, 170"
"Do not leave the Orbital Boom Sensor System running,"
"I heard something called nothing that the Cosmonauts were coming,"
"The rhymes are in place, General George Case and Peter Pace"
"Said we had absolutely no time to waste,"
"Next time we meet this whole song will be a new mix,"
"For all the Rippers out there who need a new fix,"
"My Father is Jamaican, my Mother is British,"
"Raised to be civic, in the household we spoke Yiddish"
"ELF 100 cycles per second, Elephant Hearing,"
"I'm heading for the clearing, Storm Clouds appearing, 180"
"On the back of an Elephant with advanced intelligence,"
"Like Nikola Tesla, shit!, damn that's a smart elephant,"
"Cease fire breach, riot and loot for 3 weeks, don't you see,"
"Broke niggas never promote peace,"
"Susan Malveaux will interview the polygamist Mr. Bis,"
"Undisclosed in his home by the cliffs,"
"I rip shit consistent, spit persistent,"
"The sickness, spit with conviction, promote lyrical fitness,"
I'm lost...... Which version is this? Mozart with a flowchart
Putting together parts of an unknown art 190
but coming from my own heart _________
"Burning a disk, initializing, rhyming and visualizing,  "
"Reaching 1000 Bars and climbing,"
"Martial? several miles deep underneath the Earth,"
"The Boston Visionary Cell designed my new Lab,"
"Paul Laffoley engineered a magnificent draft,"
"Extraordinary men, who meet to review and recommend,"
"I attend the Gubernatorial that never ends,"
"We just got a SASO, we call this one the Black Hole,"
"I'm glad I'm the last to go, 200"
"Zionism the answer to your uncensored question,"
"Guy de Rothschild and his bloodline brethren,"
"Playing the guitar singing folk songs, speaking my mind,"
"Nobody could really understand the reason I rhyme,"
"Infrared direct hit, target bled, proceed to inject the syringe with meds"
"that subsequently pinch your leg,"
"You feel like your an inch from being dead but you alive instead,"
"You're really dead your just living in my head,"
"Fire for effect, smoke out then rest,"
"Give me a wedge formation, roll out like this, 210"
"I will spare no sin, walk in with a scarecrow grin, looking crazy,"
"Cause that's what you made me,"
"Classified payloads with no frequency safe modes, no safety,"
"And I still made time for the ladies,"
"Ceiling visibility unlimited, a lyricist river fish"
Surrounded by nigger shrimp I'm a kiler pimp
"Somebody said Hip Hop don't need me,"
"Nigga I grew up in D.C., I love Lil' Weezy,"
"Me and Baby got the same name,"
"We probably got the same blood in our veins, liquid propane, 220"
"At the top of the Temple Mount Mosque I look at the Sun,"
"I just have a few words for everyone,"
"Everybody bow your heads and say this prayer,"
From this moment Hip Hop is united everywhere
"Poet Laureate Infinity,"
I WILL FOREVER BE THE ILLEST LYRICALLY! 226
"""
}
